## main jekyll args

##pygments: true
highlighter: rouge
permalink: /:year/:month/:day/:title/

exclude:
  - '_biblio/'
  - 'README.md'
  - '*.Rmd'
  - 'knitr-cache/'
  - '_drafts/csv/*.csv'
  - '_drafts/*.R'
  - '_drafts/*.csv'

## Metadata 
title: From the Bottom of the Heap 
tagline: the musings of a geographer
author:
  name: Gavin Simpson
  email: ucfagls@gmail.com
  givenName: Gavin
  familyName: Simpson
  publishedName: Gavin L. Simpson
  twitter: ucfagls
  github: gsimpson
keywords: Science, Palaeolimnology, Palaeoecology, R, Freshwater Ecology, Open Science, Statistics, Environmetrics, Ecology, Limnology
description: "My website and blog: research on lakes, past and present"

timezone: America/Regina

# these are available to liquid filters with: site.author.givenName, etc

## Functional configuration 
url: https://www.fromthebottomoftheheap.net

analytics: UA-7900310-7

## gems to use
##gems:
##  - jekyll-pandoc

## Use pandoc for md
markdown: pandoc
pandoc:
  format: html5
  extensions:
##    - smart
    - mathjax
    - bibliography: '_biblio/blog-biblio.bib'
##    - csl: '_biblio/freshwater-biology.csl'
    - csl: '_biblio/frontiers.csl'
    - email-obfuscation: 'references'
    - highlight-style: pygments

## For categories
category_dir: category

## For tags
tag_dir: tag
